### ISSUE TITLE
Map out workflow for an event partner

### ISSUE THREAD

**Issue by adborden** [openoakland/dos-census-events#11]
As an event partner, I need a way to request an account and submit events for approval so that I can easily on board myself and get started.

**Comment by mikeubell** [comment]
@adborden Here is a first pass at a flowchart.  We probably want more steps 
in the Input Event Form box.
![ACCCC](https://user-images.githubusercontent.com/6759416/66519679-9eb57280-ea9c-11e9-9a38-900679aa77a5.jpg)

**Comment by mikeubell** [comment]
Maybe this is better?
![ACCCC](https://user-images.githubusercontent.com/6759416/66526989-49cf2780-eaaf-11e9-9ed7-54d7ab7d05c6.jpg)

**Comment by mikeubell** [comment]
Added to README
