### ISSUE TITLE
Require logins for submitters

### ISSUE THREAD

**Issue by mikeubell** [openoakland/dos-census-events#37]
As an Administrator, I want to restrict event submission to Organizers, so that not just anyone can submit an event.

## Acceptance criteria
- [ ] An Organizer role is created with permission to submit events
- [ ] Docs exist for Admins on how to add Organizers
- [ ] A login page is linked in the footer

**Comment by adborden** [comment]
Edited to add acceptance criteria.

**Comment by mikeubell** [comment]
The county needs to decide if they want to require this.  They did not think it was necessary to start off with.

**Comment by mikeubell** [comment]
This is not required
