### ISSUE TITLE
Add all the non-calendar fields to the description when exporting

### ISSUE THREAD

**Issue by mikeubell** [openoakland/dos-census-events#68]
![Screen Shot 2019-11-16 at 3 01 49 PM](https://user-images.githubusercontent.com/6759416/69000296-0f149800-0882-11ea-95c5-7229369d5645.png)

**Comment by adborden** [comment]
Did the County specifically request this? I would not so it this way. a) I think we should research Calendar's extended properties instead of adding to the description and b) we should include a URL to the event detail page in the app which will be much cleaner integration.

**Comment by mikeubell** [comment]
I cannot find anything that says that the extended attributes can be
displayed in the calendar.  I would not say this has been asked for but I
would not think to ask since I would assume that you could see all the
information in the calendar.

**Comment by adborden** [comment]
I suggest we hold off on this for now, then. I think this will complicate syncing the Google Calendar events back into the app. For example, what if someone changes those non-calendar fields in the description?

We're not going to get every field we want to display on the Google side. We'll also learn more about what we actually need Google Calendar to do. We might end up doing a calendar per language to handle the multi-lingual bits. If we end up having an email for the organizer, Google Calendar has a field for that. Anyway, I don't think we want to tackle this just yet.

**Comment by mikeubell** [comment]
When would we sync the calendar into the app?

**Comment by mikeubell** [comment]
I think we should go with the event detail page  #56 and link that to the calendar.
