### ISSUE TITLE
Show clear success/error message after submitting an event

### ISSUE THREAD

**Issue by adborden** [openoakland/dos-census-events#78]
As an event organizer, I want a clear Success or Error message after submitting an event so that I have confidence the app is working or that I understand exactly why my event is not valid

[Django Message framework](https://docs.djangoproject.com/en/2.2/ref/contrib/messages/) makes this pretty easy.

## Acceptance criteria
- [ ] A success  message is displayed when the submission is valid
- [ ] Errors are displayed inline in the form

**Comment by mikeubell** [comment]
I think errors are displayed now?  This at least should be V1 if its not happening now.

**Comment by adborden** [comment]
Errors are displayed, but success is not. It's a jarring experience after you hit submit and see a blank form... It looks like your event just disappeared.--Aaron D BordenHuman and hackerSent from my mobileOn Nov 17, 2019 10:25 AM, Michael Ubell <notifications@github.com> wrote:I think errors are displayed now?  This at least should be V1 if its not happening now.

**Comment by mikeubell** [comment]
I think we are in agreement about what is happening.  It is just that the issue seems to indicate that errors are not displayed.

**Comment by mikeubell** [comment]
This has been fixed in #98
