### ISSUE TITLE
Integration the landing page

### ISSUE THREAD

**Issue by adborden** [openoakland/dos-census-events#96]
I believe that the [landing page](https://github.com/llkats/dos-acccc/) is meant to be integrated more closely with the Census Events app. This issue is to discuss the possiblities and identify a new issue to capture any required technical work.

**Comment by mikeubell** [comment]
> I believe that the [landing page](https://github.com/llkats/dos-acccc/) is meant to be integrated more closely with the Census Events app. This issue is to discuss the possiblities and identify a new issue to capture any required technical work.

I don't believe this is true.  The landing page is for the kiosk system that the County will be deploying for people to complete the census.  Our work here is for community organizations who are helping get the word out.  The users of the two systems are not the same (other than members of the organizations may use a kiosk at some point to complete their census, but this is a different role).

**Comment by adborden** [comment]
Ok, misremembering.
